function state = init_state(dataset)
    if ~isa(dataset, 'analysis.Dataset')
        error('Input must be an analysis.Dataset');
    end
    if ~isfield(dataset.data, 'meta')
        error('Dataset.data.meta is required.');
    end

    state = struct();
    state.Dataset = dataset;
    state.Selection = struct( ...
        'Groups', struct(), ...
        'Conditions', {{}}, ...
        'ROIs', struct(), ...
        'TimeWindows', struct(), ...
        'FreqBands', struct());
    state.Results = struct( ...
        'ERPs', struct(), ...
        'GA', struct(), ...
        'GA_TFD', struct(), ...
        'TF', struct(), ...
        'Contrasts', struct(), ...
        'Features', struct());
    % state.cfg can be added here if you want global config
end
